//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferencePoze
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evenimente", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary3", IsReference=true)]
    public partial class Evenimente : object
    {
        
        private int DelField;
        
        private int IdField;
        
        private string NumeField;
        
        private System.Collections.Generic.List<ServiceReferencePoze.Poze> PozesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Del
        {
            get
            {
                return this.DelField;
            }
            set
            {
                this.DelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePoze.Poze> Pozes
        {
            get
            {
                return this.PozesField;
            }
            set
            {
                this.PozesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Poze", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary3", IsReference=true)]
    public partial class Poze : object
    {
        
        private string CaleField;
        
        private System.DateTime Data_creareField;
        
        private int DelField;
        
        private string DescriereField;
        
        private System.Collections.Generic.List<ServiceReferencePoze.Evenimente> EvenimentesField;
        
        private int IdField;
        
        private System.Collections.Generic.List<ServiceReferencePoze.Locatii> LocatiisField;
        
        private string NumeField;
        
        private System.Collections.Generic.List<ServiceReferencePoze.Persoane> PersoanesField;
        
        private string TipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cale
        {
            get
            {
                return this.CaleField;
            }
            set
            {
                this.CaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_creare
        {
            get
            {
                return this.Data_creareField;
            }
            set
            {
                this.Data_creareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Del
        {
            get
            {
                return this.DelField;
            }
            set
            {
                this.DelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePoze.Evenimente> Evenimentes
        {
            get
            {
                return this.EvenimentesField;
            }
            set
            {
                this.EvenimentesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePoze.Locatii> Locatiis
        {
            get
            {
                return this.LocatiisField;
            }
            set
            {
                this.LocatiisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePoze.Persoane> Persoanes
        {
            get
            {
                return this.PersoanesField;
            }
            set
            {
                this.PersoanesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip
        {
            get
            {
                return this.TipField;
            }
            set
            {
                this.TipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Locatii", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary3", IsReference=true)]
    public partial class Locatii : object
    {
        
        private int DelField;
        
        private int IdField;
        
        private string NumeField;
        
        private System.Collections.Generic.List<ServiceReferencePoze.Poze> PozesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Del
        {
            get
            {
                return this.DelField;
            }
            set
            {
                this.DelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePoze.Poze> Pozes
        {
            get
            {
                return this.PozesField;
            }
            set
            {
                this.PozesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persoane", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary3", IsReference=true)]
    public partial class Persoane : object
    {
        
        private int DelField;
        
        private int IdField;
        
        private string NumeField;
        
        private System.Collections.Generic.List<ServiceReferencePoze.Poze> PozesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Del
        {
            get
            {
                return this.DelField;
            }
            set
            {
                this.DelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePoze.Poze> Pozes
        {
            get
            {
                return this.PozesField;
            }
            set
            {
                this.PozesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePoze.Interface")]
    public interface Interface
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/AddEveniment", ReplyAction="http://tempuri.org/Interface/AddEvenimentResponse")]
        System.Threading.Tasks.Task AddEvenimentAsync(string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/AddLocatie", ReplyAction="http://tempuri.org/Interface/AddLocatieResponse")]
        System.Threading.Tasks.Task AddLocatieAsync(string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/AddPersoana", ReplyAction="http://tempuri.org/Interface/AddPersoanaResponse")]
        System.Threading.Tasks.Task AddPersoanaAsync(string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/AddPoza", ReplyAction="http://tempuri.org/Interface/AddPozaResponse")]
        System.Threading.Tasks.Task AddPozaAsync(string cale, string nume, string tip, string descriere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/DelEveniment", ReplyAction="http://tempuri.org/Interface/DelEvenimentResponse")]
        System.Threading.Tasks.Task DelEvenimentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/DelLocatie", ReplyAction="http://tempuri.org/Interface/DelLocatieResponse")]
        System.Threading.Tasks.Task DelLocatieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/DelPersoana", ReplyAction="http://tempuri.org/Interface/DelPersoanaResponse")]
        System.Threading.Tasks.Task DelPersoanaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/DelPoza", ReplyAction="http://tempuri.org/Interface/DelPozaResponse")]
        System.Threading.Tasks.Task DelPozaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/GetEveniment", ReplyAction="http://tempuri.org/Interface/GetEvenimentResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePoze.Evenimente>> GetEvenimentAsync(string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/GetLocatie", ReplyAction="http://tempuri.org/Interface/GetLocatieResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePoze.Locatii>> GetLocatieAsync(string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/GetPersoana", ReplyAction="http://tempuri.org/Interface/GetPersoanaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePoze.Persoane>> GetPersoanaAsync(string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/GetPoza", ReplyAction="http://tempuri.org/Interface/GetPozaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePoze.Poze>> GetPozaAsync(string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/UpEveniment", ReplyAction="http://tempuri.org/Interface/UpEvenimentResponse")]
        System.Threading.Tasks.Task UpEvenimentAsync(int id, string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/UpLocatie", ReplyAction="http://tempuri.org/Interface/UpLocatieResponse")]
        System.Threading.Tasks.Task UpLocatieAsync(int id, string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/UpPersoana", ReplyAction="http://tempuri.org/Interface/UpPersoanaResponse")]
        System.Threading.Tasks.Task UpPersoanaAsync(int id, string nume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/UpPoza", ReplyAction="http://tempuri.org/Interface/UpPozaResponse")]
        System.Threading.Tasks.Task UpPozaAsync(int id, string cale, string nume, string tip, string descriere);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface InterfaceChannel : ServiceReferencePoze.Interface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class InterfaceClient : System.ServiceModel.ClientBase<ServiceReferencePoze.Interface>, ServiceReferencePoze.Interface
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InterfaceClient() : 
                base(InterfaceClient.GetDefaultBinding(), InterfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Interface.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceClient(EndpointConfiguration endpointConfiguration) : 
                base(InterfaceClient.GetBindingForEndpoint(endpointConfiguration), InterfaceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InterfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InterfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddEvenimentAsync(string nume)
        {
            return base.Channel.AddEvenimentAsync(nume);
        }
        
        public System.Threading.Tasks.Task AddLocatieAsync(string nume)
        {
            return base.Channel.AddLocatieAsync(nume);
        }
        
        public System.Threading.Tasks.Task AddPersoanaAsync(string nume)
        {
            return base.Channel.AddPersoanaAsync(nume);
        }
        
        public System.Threading.Tasks.Task AddPozaAsync(string cale, string nume, string tip, string descriere)
        {
            return base.Channel.AddPozaAsync(cale, nume, tip, descriere);
        }
        
        public System.Threading.Tasks.Task DelEvenimentAsync(int id)
        {
            return base.Channel.DelEvenimentAsync(id);
        }
        
        public System.Threading.Tasks.Task DelLocatieAsync(int id)
        {
            return base.Channel.DelLocatieAsync(id);
        }
        
        public System.Threading.Tasks.Task DelPersoanaAsync(int id)
        {
            return base.Channel.DelPersoanaAsync(id);
        }
        
        public System.Threading.Tasks.Task DelPozaAsync(int id)
        {
            return base.Channel.DelPozaAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePoze.Evenimente>> GetEvenimentAsync(string nume)
        {
            return base.Channel.GetEvenimentAsync(nume);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePoze.Locatii>> GetLocatieAsync(string nume)
        {
            return base.Channel.GetLocatieAsync(nume);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePoze.Persoane>> GetPersoanaAsync(string nume)
        {
            return base.Channel.GetPersoanaAsync(nume);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePoze.Poze>> GetPozaAsync(string nume)
        {
            return base.Channel.GetPozaAsync(nume);
        }
        
        public System.Threading.Tasks.Task UpEvenimentAsync(int id, string nume)
        {
            return base.Channel.UpEvenimentAsync(id, nume);
        }
        
        public System.Threading.Tasks.Task UpLocatieAsync(int id, string nume)
        {
            return base.Channel.UpLocatieAsync(id, nume);
        }
        
        public System.Threading.Tasks.Task UpPersoanaAsync(int id, string nume)
        {
            return base.Channel.UpPersoanaAsync(id, nume);
        }
        
        public System.Threading.Tasks.Task UpPozaAsync(int id, string cale, string nume, string tip, string descriere)
        {
            return base.Channel.UpPozaAsync(id, cale, nume, tip, descriere);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Interface))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Interface))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InterfaceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Interface);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InterfaceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Interface);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Interface,
        }
    }
}
